name: flame_learn_sheet_music
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  melos: ^7.8.1

workspace:
  - apps/learn_sheet_music
  - packages/audio_audioplayers
  - packages/audio_soundpool
  - packages/examples
  - packages/midi_input
  - packages/midi_messages
  - packages/music_stave
  - packages/musiqwik_font
  - packages/note_sequence
  - packages/piano_widget/piano_widget
  - packages/piano_widget/example
  - packages/simple_piano/simple_piano
  - packages/simple_piano/simple_piano_keylistener
  - packages/simple_piano/simple_piano_waterfall
  - packages/sound_service/sound_service
  - packages/sound_service/sound_service_assets
  - packages/sound_service/sound_service_util
  - packages/tone_generator/tone_generator
  - packages/tone_generator/example
  - packages/virtual_keyboard_status
  - packages/virtual_piano/virtual_piano
  - packages/virtual_piano/example
  # I think these two are obsolete, but keeping them until cleanup
  - packages/music_score
  - packages/sf2_player

melos:
  repository: https://github.com/tolland/flame_learn_sheet_music
  useRootAsPackage: true
  command:
    bootstrap:
      # Avoid concurrent pub requests,
      # remove when https://github.com/dart-lang/pub/issues/3404 is fixed
      runPubGetInParallel: false
  scripts:
    lint:all:
      run: melos run analyze && melos run format
      description: Run all static analysis checks.
    analyze:
      run: |
        melos exec -c 1 -- \
          flutter analyze --fatal-infos
      description: Run `flutter analyze` for all packages.
    format:
      run: melos exec dart format . --fix
      description: Run `dart format` for all packages.
    clean:
      run: melos exec -c 1 -- flutter clean
      description: Clean all packages

flutter:
  uses-material-design: true