name: music_score
description: "A flutter widget to display music score"
version: 0.0.1
homepage: https://github.com/tolland/music_score

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  dashbook: ^0.1.13
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  logging: ^1.2.0
  musiqwik_font: ^0.0.5
  note_sequence: ^0.0.1

dependency_overrides:
  musiqwik_font:
    path: ../musiqwik_font
  note_sequence:
    path: ../note_sequence


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.24.9

flutter:
    uses-material-design: true
    assets:
        - assets/
#    fonts:
#      - family: MusiQwik
#        fonts:
#          - asset: fonts/Musiqwik-zRl1.ttf
