name: simple_piano_waterfall
resolution: workspace
description: "A flutter widget to display a piano waterfall visualization."
version: 0.0.1
homepage: https://github.com/tolland/piano_waterfall

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.2.0
  sound_service_util: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.8

# The following section is specific to Flutter packages.
flutter:
