// Mocks generated by Mockito 5.4.4 from annotations
// in sound_service/test/sound_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i10;

import 'package:audio_audioplayers/model/player_locker.dart' as _i8;
import 'package:audio_audioplayers/repositories/audio_controller.dart' as _i6;
import 'package:audio_audioplayers/repositories/audioplayer_pools.dart' as _i11;
import 'package:audioplayers/audioplayers.dart' as _i7;
import 'package:flutter/widgets.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:pool/pool.dart' as _i3;
import 'package:sound_service/sound_service.dart' as _i4;
import 'package:stop_watch_timer/stop_watch_timer.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeStopWatchTimer_0 extends _i1.SmartFake
    implements _i2.StopWatchTimer {
  _FakeStopWatchTimer_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDuration_1 extends _i1.SmartFake implements Duration {
  _FakeDuration_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePool_2 extends _i1.SmartFake implements _i3.Pool {
  _FakePool_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [IInstrumentRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockInstrumentRepository extends _i1.Mock
    implements _i4.IInstrumentRepository {
  @override
  _i5.Future<List<int>> getPitchList() => (super.noSuchMethod(
        Invocation.method(
          #getPitchList,
          [],
        ),
        returnValue: _i5.Future<List<int>>.value(<int>[]),
        returnValueForMissingStub: _i5.Future<List<int>>.value(<int>[]),
      ) as _i5.Future<List<int>>);
}

/// A class which mocks [Clock].
///
/// See the documentation for Mockito's code generation for more information.
class MockClock extends _i1.Mock implements _i4.Clock {
  @override
  double get ticksPerSecond => (super.noSuchMethod(
        Invocation.getter(#ticksPerSecond),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  set ticksPerSecond(double? value) => super.noSuchMethod(
        Invocation.setter(
          #ticksPerSecond,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.StopWatchTimer get stopWatchTimer => (super.noSuchMethod(
        Invocation.getter(#stopWatchTimer),
        returnValue: _FakeStopWatchTimer_0(
          this,
          Invocation.getter(#stopWatchTimer),
        ),
        returnValueForMissingStub: _FakeStopWatchTimer_0(
          this,
          Invocation.getter(#stopWatchTimer),
        ),
      ) as _i2.StopWatchTimer);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void pause() => super.noSuchMethod(
        Invocation.method(
          #pause,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void resume() => super.noSuchMethod(
        Invocation.method(
          #resume,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void stop() => super.noSuchMethod(
        Invocation.method(
          #stop,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setTrackDuration({required Duration? duration}) => super.noSuchMethod(
        Invocation.method(
          #setTrackDuration,
          [],
          {#duration: duration},
        ),
        returnValueForMissingStub: null,
      );

  @override
  Duration passedTime({required Duration? trackDuration}) =>
      (super.noSuchMethod(
        Invocation.method(
          #passedTime,
          [],
          {#trackDuration: trackDuration},
        ),
        returnValue: _FakeDuration_1(
          this,
          Invocation.method(
            #passedTime,
            [],
            {#trackDuration: trackDuration},
          ),
        ),
        returnValueForMissingStub: _FakeDuration_1(
          this,
          Invocation.method(
            #passedTime,
            [],
            {#trackDuration: trackDuration},
          ),
        ),
      ) as Duration);

  @override
  _i5.Stream<Duration> passedTimeStream({required Duration? trackDuration}) =>
      (super.noSuchMethod(
        Invocation.method(
          #passedTimeStream,
          [],
          {#trackDuration: trackDuration},
        ),
        returnValue: _i5.Stream<Duration>.empty(),
        returnValueForMissingStub: _i5.Stream<Duration>.empty(),
      ) as _i5.Stream<Duration>);

  @override
  void start() => super.noSuchMethod(
        Invocation.method(
          #start,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AudioController].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioController extends _i1.Mock implements _i6.AudioController {
  @override
  Map<int, _i7.Source> get assetSources => (super.noSuchMethod(
        Invocation.getter(#assetSources),
        returnValue: <int, _i7.Source>{},
        returnValueForMissingStub: <int, _i7.Source>{},
      ) as Map<int, _i7.Source>);

  @override
  List<List<_i8.PlayerLocker?>> get audioMatrix => (super.noSuchMethod(
        Invocation.getter(#audioMatrix),
        returnValue: <List<_i8.PlayerLocker?>>[],
        returnValueForMissingStub: <List<_i8.PlayerLocker?>>[],
      ) as List<List<_i8.PlayerLocker?>>);

  @override
  set audioMatrix(List<List<_i8.PlayerLocker?>>? _audioMatrix) =>
      super.noSuchMethod(
        Invocation.setter(
          #audioMatrix,
          _audioMatrix,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void attachDependencies(
          _i9.ValueNotifier<_i10.AppLifecycleState>? lifecycleNotifier) =>
      super.noSuchMethod(
        Invocation.method(
          #attachDependencies,
          [lifecycleNotifier],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void reduceVolumeGradually(_i8.PlayerLocker? playa) => super.noSuchMethod(
        Invocation.method(
          #reduceVolumeGradually,
          [playa],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void stopNote(
    int? pitch,
    int? channel,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #stopNote,
          [
            pitch,
            channel,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> playNote({
    required int? pitch,
    required int? velocity,
    required int? channel,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #playNote,
          [],
          {
            #pitch: pitch,
            #velocity: velocity,
            #channel: channel,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [AudioControllerPools].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioControllerPools extends _i1.Mock
    implements _i11.AudioControllerPools {
  @override
  _i3.Pool get pool => (super.noSuchMethod(
        Invocation.getter(#pool),
        returnValue: _FakePool_2(
          this,
          Invocation.getter(#pool),
        ),
        returnValueForMissingStub: _FakePool_2(
          this,
          Invocation.getter(#pool),
        ),
      ) as _i3.Pool);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void reduceVolumeGradually(_i7.AudioPlayer? playa) => super.noSuchMethod(
        Invocation.method(
          #reduceVolumeGradually,
          [playa],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void stopNote(int? pitch) => super.noSuchMethod(
        Invocation.method(
          #stopNote,
          [pitch],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> playNote({
    required int? pitch,
    required int? velocity,
    required int? channel,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #playNote,
          [],
          {
            #pitch: pitch,
            #velocity: velocity,
            #channel: channel,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
