name: virtual_piano
description: widget that displays a keyboard for piano
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  #piano_widget: ^1.3.0
  logging: ^1.2.0
  piano_widget:
    path: ../piano_widget

dev_dependencies:
  lints: ^2.1.0
  melos: ^3.2.0

flutter:
  uses-material-design: true
