name: sound_service
resolution: workspace
description: "Sound service bloc to handle audio playback."
version: 0.0.1
homepage: https://github.com/tolland/sound_service

environment:
  sdk: '>=3.10.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  assets_audio_player_updated: ^3.1.1
  audio_audioplayers: any
  audioplayers: ^6.7.1
  bloc: ^8.1.4
  bloc_concurrency: ^0.2.3
  dart_midi: any
  equatable: ^2.0.5
  file_picker: ^11.0.2
  flutter_bloc: ^8.1.3
  freezed_annotation: ^3.1.0
  json_annotation: ^4.8.1
  logging: ^1.2.0
  pool: ^1.5.1
  simple_piano: any
  sound_service_util: any
  soundpool: any
  stop_watch_timer: ^3.0.2
  synchronized: ^3.1.0+1
  tonic: ^0.2.4
  audioplayers_platform_interface: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  bloc_test: ^9.1.5
  build_runner: ^2.4.8
  freezed: ^3.1.0
  json_serializable: ^6.7.1
  mockito: ^5.4.4

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/notes/
    - assets/sfx/
    - assets/images/
