name: sound_service_util
description: simple methods
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  logging: ^1.2.0
  ansi_codes: ^0.1.1

dev_dependencies:
  lints: ^2.1.0
  melos: ^3.2.0

flutter:
  uses-material-design: true
