name: midi_input
resolution: workspace
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_midi_command: ^0.4.15
  logging: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
